import { NextResponse } from 'next/server';
import { evaluateAll } from '@/app/lib/strategies';
import type { FinancialSnapshot } from '@/app/lib/strategies';

const TEST_SNAPSHOT: FinancialSnapshot = {
  w2Income:             243_500,
  bonusIncome:          111_692,
  bonusDeferred:              0,
  bonusTakenAsCash:     111_692,
  income1099:             6_600,
  carAllowanceAnnual:         0,
  otherIncomeAnnual:          0,
  spouseWorks:          false,
  filingStatus:         'mfj',
  state:                'CA',
  dependentsUnder18:    1,
  dependentAges:        '14',
  hasBusinessEntity:              true,
  businessRevenue:                5_000,
  primaryBusinessNetProfit:       4_000,
  primaryBusinessType:            'smllc',
  primaryHoursPerWeekInBusiness:  5,
  hasDedicatedHomeOffice:         false,
  homeOfficeSquareFootage:        0,
  isNewBusiness:                  false,
  startupCostsIncurred:           0,
  spouseW2Income:                 0,
  spouseBusinessRevenue:          0,
  spouseBusinessNetProfit:        0,
  spouseBusinessType:             '',
  spouseHoursPerWeekInBusiness:   0,
  currentTaxPaid:       110_000,
  hasHsaAvailable:      false,
  hasCpa:               false,
  cpaProactive:         false,
  primaryResidenceValue:  690_000,
  mortgageBalance:        200_000,
  homeEquity:             490_000,
  currentlyOwnsRental:  true,   // owns rental → depreciation + REPS become ACTIVE
  rentalPropertyValue:  350_000,
  rentalMortgageBalance: 200_000,
  retirementBalance:    200_000,
  traditionalIraBalance:  300,
  taxableBrokerageBalance: 50_000,
  businessEquityValue:    0,
  monthlyRentalIncome:    2_200,
  monthlyDividendIncome:  0,
  essentialMonthlySpend:  5_000,
  discretionaryMonthlySpend: 3_300,
  monthlySpend:           8_300,
  emergencyFund:          13_000,
  extraDebtPayments:      0,
  childSupportMonthly:    0,
  alimonyMonthly:         0,
  carLoanBalance:         0,
  carLoanRate:            0,
  carLoanPayment:         0,
  studentLoanBalance:     0,
  studentLoanRate:        0,
  studentLoanPayment:     0,
  personalLoanBalance:    0,
  personalLoanRate:       0,
  personalLoanPayment:    0,
  creditCardBalance:      0,
  creditCardRate:         0,
  creditCardPayment:      0,
  businessLoanBalance:    0,
  businessLoanRate:       0,
  businessLoanPayment:    0,
  otherDebtLabel:         '',
  otherDebtBalance:       0,
  otherDebtRate:          0,
  otherDebtPayment:       0,
  debts:                  [],
  employer401kAllowsAfterTax: false,
  consideringRealEstate:  false,
  plannedPropertyValue:   undefined,
  repsQualified:          undefined,
};

export function GET() {
  const results = evaluateAll(TEST_SNAPSHOT);
  return NextResponse.json(
    { snapshot: TEST_SNAPSHOT, results },
    { headers: { 'Content-Type': 'application/json; charset=utf-8' } },
  );
}
