'use client';

import { useMemo } from 'react';
import { clearHomeOfficeAnswers, clearStartupCostAnswers, clearVehicleAnswers, type TaxSituationFormState } from '@/app/lib/audit/taxSituationFlow';
import { useQuestionFlow } from '@/app/lib/useQuestionFlow';
import { ChoiceList, DollarAnswer, IncomeQuestion, NumberAnswer, YesNo } from '@/components/audit/IncomeQuestion';

type TaxStep = 'filing-status' | 'state' | 'tax-paid' | 'business-question' | 'business-revenue' | 'business-profit' | 'business-type' | 'business-hours' | 'spouse-business-question' | 'spouse-business-type' | 'home-office-question' | 'home-office-sqft' | 'startup-question' | 'startup-costs' | 'vehicle-question' | 'vehicle-price' | 'vehicle-use' | 'hsa' | 'after-tax-401k' | 'cpa-question' | 'cpa-proactive';
type SpouseIncomeType = '' | 'w2' | 'self_employment' | 'both';

const ALL_TAX_STEPS: readonly TaxStep[] = ['filing-status', 'state', 'tax-paid', 'business-question', 'business-revenue', 'business-profit', 'business-type', 'business-hours', 'spouse-business-question', 'spouse-business-type', 'home-office-question', 'home-office-sqft', 'startup-question', 'startup-costs', 'vehicle-question', 'vehicle-price', 'vehicle-use', 'hsa', 'after-tax-401k', 'cpa-question', 'cpa-proactive'];
const BUSINESS_TYPES = [['sole_prop', 'Sole proprietorship'], ['smllc', 'Single-member LLC'], ['scorp', 'S-Corp'], ['partnership', 'Partnership']] as const;
const STATE_OPTIONS = [['CA', 'California (CA)'], ['NY', 'New York (NY)'], ['NJ', 'New Jersey (NJ)'], ['TX', 'Texas (TX)'], ['FL', 'Florida (FL)'], ['WA', 'Washington (WA)'], ['NV', 'Nevada (NV)'], ['OTHER', 'Other']] as const;

/** Runs Tax Situation as a local-only, conditional one-question flow. */
export function AuditTaxSituationFlow({ form, spouseWorks, spouseIncomeType, onChange, onComplete }: { form: TaxSituationFormState; spouseWorks: boolean; spouseIncomeType: SpouseIncomeType; onChange: (changes: Partial<TaxSituationFormState>) => void; onComplete: () => void }) {
  const spouseCanHaveBusiness = spouseWorks && (spouseIncomeType === 'self_employment' || spouseIncomeType === 'both');
  const steps = useMemo(() => getTaxSteps(form, spouseCanHaveBusiness, spouseWorks), [form, spouseCanHaveBusiness, spouseWorks]);
  const flow = useQuestionFlow(steps, ALL_TAX_STEPS.length);
  const next = (step: TaxStep) => flow.goTo(step);
  const question = (title: string, explainer: string | undefined, content: React.ReactNode, onNext: () => void, showNext = true, label?: string) => <IncomeQuestion title={title} explainer={explainer} step={flow.currentIndex + 1} totalSteps={flow.totalSteps} onBack={flow.back} onNext={onNext} showNext={showNext} nextLabel={label}>{content}</IncomeQuestion>;

  switch (flow.currentStep) {
    case 'filing-status': return question('How do you file your taxes?', undefined, <ChoiceList choices={[['mfj', 'Married, filing jointly'], ['single', 'Single'], ['hoh', 'Head of household']] as const} value={form.filingStatus} onSelect={(filingStatus) => { onChange({ filingStatus }); next('state'); }} />, onComplete, false);
    case 'state': return question('What state do you live in?', undefined, <select autoFocus value={form.state} onChange={(event) => onChange({ state: event.target.value })} className="min-h-14 w-full rounded-xl border border-gray-200 bg-white px-4 text-base font-semibold text-gray-900 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20">{STATE_OPTIONS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>, () => next('tax-paid'));
    case 'tax-paid': return question('About how much did you pay in federal and state taxes last year?', 'Add up what was withheld from your paychecks (box 2 on your W-2) plus any extra estimated payments you made directly to the IRS or your state.', <DollarAnswer value={form.currentTaxPaid} onChange={(currentTaxPaid) => onChange({ currentTaxPaid })} />, () => next('business-question'));
    case 'business-question': return question('Do you own a business or LLC?', 'This includes any self-employment — a sole proprietorship, a single-member LLC, an S-Corp, or a partnership. If you freelance or consult on the side, that counts.', <YesNo onYes={() => { onChange({ hasBusinessEntity: true }); next('business-revenue'); }} onNo={() => { onChange({ hasBusinessEntity: false }); next(spouseCanHaveBusiness ? 'spouse-business-question' : 'hsa'); }} />, onComplete, false);
    case 'business-revenue': return question("What's your business's gross revenue?", 'Total money the business brought in, before any expenses.', <DollarAnswer value={form.businessRevenue} onChange={(businessRevenue) => onChange({ businessRevenue })} />, () => next('business-profit'));
    case 'business-profit': return question("What's your business's net profit?", "What's left after expenses — this is the amount that actually gets taxed.", <DollarAnswer value={form.primaryBusinessNetProfit} onChange={(primaryBusinessNetProfit) => onChange({ primaryBusinessNetProfit })} />, () => next('business-type'));
    case 'business-type': return question('What type of business is it?', undefined, <ChoiceList choices={BUSINESS_TYPES} value={form.primaryBusinessType as typeof BUSINESS_TYPES[number][0]} onSelect={(primaryBusinessType) => { onChange({ primaryBusinessType }); next('business-hours'); }} />, onComplete, false);
    case 'business-hours': return question('About how many hours a week do you spend on it?', 'This affects which tax strategies you qualify for, like a Solo 401(k) or electing S-Corp tax treatment.', <NumberAnswer suffix="hrs/wk" value={form.primaryHoursPerWeekInBusiness} onChange={(primaryHoursPerWeekInBusiness) => onChange({ primaryHoursPerWeekInBusiness })} />, () => next(spouseCanHaveBusiness ? 'spouse-business-question' : 'home-office-question'));
    case 'spouse-business-question': return question('Does your spouse have a separate business?', undefined, <YesNo onYes={() => { onChange({ spouseHasSeparateBusiness: true }); next('spouse-business-type'); }} onNo={() => { onChange({ spouseHasSeparateBusiness: false, spouseBusinessType: '' }); next(form.hasBusinessEntity ? 'home-office-question' : 'hsa'); }} />, onComplete, false);
    case 'spouse-business-type': return question('What type of business is it?', undefined, <ChoiceList choices={BUSINESS_TYPES} value={form.spouseBusinessType as typeof BUSINESS_TYPES[number][0]} onSelect={(spouseBusinessType) => { onChange({ spouseBusinessType }); next('home-office-question'); }} />, onComplete, false);
    case 'home-office-question': return question('Do you have a dedicated space you use only for this business?', "The IRS requires the space be used regularly and exclusively for business — a desk in the family room doesn't qualify, a spare room used only for work does.", <YesNo onYes={() => { onChange({ hasDedicatedHomeOffice: true }); next('home-office-sqft'); }} onNo={() => { onChange(clearHomeOfficeAnswers()); next('startup-question'); }} />, onComplete, false);
    case 'home-office-sqft': return question('About how many square feet is that space?', 'Used to calculate your home office deduction (currently $5 per square foot, up to 300 sq ft).', <NumberAnswer suffix="sq ft" value={form.homeOfficeSquareFootage} onChange={(homeOfficeSquareFootage) => onChange({ homeOfficeSquareFootage })} />, () => next('startup-question'));
    case 'startup-question': return question('Has the business been running for less than 2 years?', undefined, <YesNo onYes={() => { onChange({ isNewBusiness: true }); next('startup-costs'); }} onNo={() => { onChange(clearStartupCostAnswers()); next('vehicle-question'); }} />, onComplete, false);
    case 'startup-costs': return question('How much did you spend getting it started, before it opened?', 'Things like market research, advertising, training, or professional fees paid before you made your first sale.', <DollarAnswer value={form.startupCostsIncurred} onChange={(startupCostsIncurred) => onChange({ startupCostsIncurred })} />, () => next('vehicle-question'));
    case 'vehicle-question': return question('Is the business buying or does it own a large vehicle — a heavy-duty SUV or truck?', 'This applies to vehicles with a gross weight over 6,000 lbs — most full-size SUVs and pickup trucks qualify. This unlocks a specific tax deduction.', <YesNo onYes={() => { onChange({ hasHeavyVehicle: true }); next('vehicle-price'); }} onNo={() => { onChange(clearVehicleAnswers()); next('hsa'); }} />, onComplete, false);
    case 'vehicle-price': return question("What's the vehicle's purchase price?", undefined, <DollarAnswer value={form.vehiclePurchasePrice} onChange={(vehiclePurchasePrice) => onChange({ vehiclePurchasePrice })} />, () => next('vehicle-use'));
    case 'vehicle-use': return question('About what percentage of the time is it used for business, not personal use?', 'Needs to be over 50% to qualify. Keep a mileage log as proof.', <NumberAnswer suffix="%" value={form.vehicleBusinessUsePercent} onChange={(vehicleBusinessUsePercent) => onChange({ vehicleBusinessUsePercent })} />, () => next('hsa'));
    case 'hsa': return question('Does your employer offer a Health Savings Account (HSA)?', "Only available if you have a High-Deductible Health Plan — check your benefits if you're not sure.", <YesNo onYes={() => { onChange({ hasHsaAvailable: true }); next('after-tax-401k'); }} onNo={() => { onChange({ hasHsaAvailable: false }); next('after-tax-401k'); }} />, onComplete, false);
    case 'after-tax-401k': return question('Does your 401(k) allow after-tax contributions, beyond the normal limit?', "This is what enables a strategy called the 'mega backdoor Roth' — check with your plan administrator if you're not sure.", <ChoiceList choices={[['yes', 'Yes'], ['no', 'No'], ['unknown', 'Not sure']] as const} value={form.employer401kAllowsAfterTax === true ? 'yes' : form.employer401kAllowsAfterTax === false ? 'no' : 'unknown'} onSelect={(answer) => { onChange({ employer401kAllowsAfterTax: answer === 'yes' ? true : answer === 'no' ? false : undefined }); next('cpa-question'); }} />, onComplete, false);
    case 'cpa-question': return question('Do you work with a CPA or tax professional?', undefined, <YesNo onYes={() => { onChange({ hasCpa: true }); next('cpa-proactive'); }} onNo={() => { onChange({ hasCpa: false, cpaProactive: undefined }); onComplete(); }} />, onComplete, false);
    case 'cpa-proactive': return question('What does your CPA do?', undefined, <ChoiceList choices={[['proactive', 'Proactively suggests strategies'], ['filing', 'Mainly just files my return']] as const} value={form.cpaProactive === true ? 'proactive' : 'filing'} onSelect={(answer) => { onChange({ cpaProactive: answer === 'proactive' }); onComplete(); }} />, onComplete, false, 'Continue to balance sheet →');
  }
}

/** Builds the active Tax Situation path from the local answers. */
function getTaxSteps(form: TaxSituationFormState, spouseCanHaveBusiness: boolean, spouseWorks: boolean): TaxStep[] {
  const effectiveBusiness = form.hasBusinessEntity || (spouseWorks && form.spouseHasSeparateBusiness);
  return ['filing-status', 'state', 'tax-paid', 'business-question', ...(form.hasBusinessEntity ? ['business-revenue', 'business-profit', 'business-type', 'business-hours'] : []), ...(spouseCanHaveBusiness ? ['spouse-business-question', ...(form.spouseHasSeparateBusiness ? ['spouse-business-type'] : [])] : []), ...(effectiveBusiness ? ['home-office-question', ...(form.hasDedicatedHomeOffice ? ['home-office-sqft'] : []), 'startup-question', ...(form.isNewBusiness ? ['startup-costs'] : []), 'vehicle-question', ...(form.hasHeavyVehicle ? ['vehicle-price', 'vehicle-use'] : [])] : []), 'hsa', 'after-tax-401k', 'cpa-question', ...(form.hasCpa ? ['cpa-proactive'] : [])] as TaxStep[];
}
